### ISSUE TITLE
Not able to download multiple bhavcopies in loop

### ISSUE THREAD

**Issue by gaurav-260** [anoopjangra/pynse#2]
I am trying to download bhavcopy using a loop and iterate it over multiple days. It works perfectly fine for 1 day, but over multiple days (even 2 days) gives an error as "BadZipFile: File is not a zip file". Would you be able to help out?

Attached is the code I am running.

Thanks in advance, the library is immensely useful.

Below is the code:
## Downloading bhavcopy
start_date = date(2020, 2, 1) #enter start date
end_date = date(2020, 2, 4) #enter end date
single_date=start_date
while single_date < end_date:
    my_date = single_date.strftime("%Y-%m-%d")
    my_date = datetime.datetime.strptime(my_date, "%Y-%m-%d")
    my_date_year= my_date.year # To Get year from date
    my_date_month= my_date.month # To Get month from date
    my_date_day= my_date.day # To Get date from date
    print (my_date)
    print (my_date_year,"--",my_date_month,'--',my_date_day)
    single_date=single_date + timedelta(days=1)
    bhav=nse.bhavcopy_fno(dt.date(my_date_year,my_date_month,my_date_day))

**Comment by anoopjangra** [comment]
upgrade pynse 

`pip install pynse==0.1.4`

and to download multiple files loop through nse.trading_days()
